# 汉字自动拆分系统配置文件：现代五笔

schema:
  schema_id: xdwb
  name: 五笔字型 98 版
  version: "0.1"
  author:
    - 发明人 李明
    - 重建人 蓝落萧 2320693692@qq.com
  description: |
    用于测试自动拆分

selector:
  - 笔顺优先
  - 根少优先
  - 能连不交、能散不连
  - 取大优先

classifier:
  1: [横, 提]
  2: [竖, 竖钩]
  3: [撇]
  4: [点, 捺]
  5: [横钩, 横撇, 横折, 横折钩, 横斜钩, 横折提, 横折折, 横折弯, 横撇弯钩, 横折弯钩, 横折折撇, 横折折折, 横折折折钩, 弯钩]
  6: [竖提, 竖折, 竖弯, 竖弯钩, 竖折撇, 竖折折钩, 竖折折, 撇点, 撇折, 斜钩]

mapper:
  q: [金, 钅, 方, 刀, 勹, 刂]
  w: [言, 讠, 4, 亠, 立, ]
  e: [心, 忄, 2, 占上, 尚上, 卜, 卜离, 古]
  r: [禾, 余下, 3, 采上, 每上, 撇二横, 气]
  t: [土, 士, 干, 举下]
  y: [又, 经角, 予上, 厶, 虫, 肆左]
  u: [竹, 竹头, 八, 宀, 冖, 小, 不下, 步中]
  i: [人, 亻]
  o: [文, 攵, 夂, 夕, 久上, 火, 灬, 雨]
  p: [目, 尸, 声下, 隹右, 反外, 段二, 乐二, 抑中, 止, 足旁, 止变, 足]
  a: [西, 女, 大, 弓]
  s: [石, 1, 舞中]
  d: [米, 两撇, 彳, 二, 工, 齐下, 临左, 冫, 丬, 总上, 前上, 前上离]
  f: [日, 三, 彐, 五, 青上, 曰, 横日, 冒上]
  g: [广, 疒, 厂, 皮二, 十, 门]
  h: [廿, 艹, 廾, 黄上, 贝, 其, 具上]
  j: [丁, 扌, 寸, 手, 看上, 着中, 5]
  k: [口]
  l: [王, 母二, 贯二, 衤, 礻, 七, 匕, 化右, 化右变, 比左, 弋, 戈, 戋, 6]
  z: [之, 舟, 辶, 廴, 斤, 豸, 豕, 豕下, 马, 犭]
  x: [白, 臼, 义下, 彡, 幺, 双折, 纟]
  c: [田, 囗, 匚, 凵, 假角, 候角, 冂, 见二, 皿, 央三, 罗上, 黑五, 四, 官下, 山, 川, 三竖]
  v: [水, 泰下, 鳏角, 脊外, 承外, 氵, 兴上, 展底, 衣下, 已, 己, 巳, 也, 巴, 卷下]
  b: [子, 孑, 了, 耳, 卩, 阝, 几, 儿, 流角]
  n: [月, 那左, 而上, 有上, 乃, 力, 用, 九]
  m: [木, 巾, 兼下, 亦下, 变中, 业上]

aliaser:
  步中: {source: 步下, indexList: [0, 1]}
  段二: {source: 段左, indexList: [0, 1]}
  母二: {source: 母, indexList: [0, 1]}
  贯二: {source: 母, indexList: [0, 1]}
  央三: {source: 央, indexList: [0, 1, 2]}
  业上: {source: 业, indexList: [0, 1, 2, 3]}
  皮二: {source: 皮, indexList: [0, 1]}
  舞中: {source: 舞上, indexList: [2, ..., 6]}
  着中: {source: 差上, indexList: [2, ..., 5]}
  乐二: {source: 乐, indexList: [0, 1]}
  不下: {source: 不, indexList: [1, 2, 3]}
  余下: {source: 余, indexList: [2, ..., 6]}
  撇二横: {source: 朱, indexList: [0, 1, 2]}
  夫上: {source: 夫, indexList: [0, 1, 2]}
  年下: {source: 年, indexList: [2, ..., 5]}
  革下: {source: 革, indexList: [4, ..., 8]}
  于下: {source: 于, indexList: [1, 2]}
  其上: {source: 其, indexList: [0, ..., 5]}
  寒中: {source: 媾右, indexList: [0, ..., 4]}
  东上: {source: 东, indexList: [0, 1]}
  弋左: {source: 弋, indexList: [0, 1]}
  牙上: {source: 牙, indexList: [0, 1]}
  具上: {source: 具, indexList: [0, ..., 5]}
  三竖: {source: 带上, indexList: [1, 2, 3]}
  四竖: {source: 舞上, indexList: [3, ..., 6]}
  曾中: {source: 曾上, indexList: [2, ..., 7]}
  身框: {source: 身, indexList: [1, 2]}
  两撇: {source: 勿, indexList: [2, 3]}
  且上: {source: 且, indexList: [0, ..., 3]}
  豕下: {source: 豕, indexList: [1, ..., 6]}
  臼裂: {source: 舆框, indexList: [0, ..., 6]}
  展底: {source: 展内, indexList: [4, 5, 6]}
  久上: {source: 久, indexList: [0, 1]}
  见下: {source: 见, indexList: [2, 3]}
  鱼上: {source: 鱼, indexList: [0, ..., 6]}
  犭二: {source: 犭, indexList: [0, 1]}
  万下: {source: 万, indexList: [1, 2]}
  隹右: {source: 隹, indexList: [2, ..., 7]}
  羊变: {source: 羌, indexList: [0, ..., 5]}
  舟下: {source: 舟, indexList: [1, ..., 5]}
  脊外: {source: 脊上, indexList: [0, ..., 3]}
  承外: {source: 承, indexList: [5, 6, 7]}
  兴上: {source: 兴, indexList: [0, 1, 2]}
  亦下: {source: 亦, indexList: [2, ..., 5]}
  变中: {source: 变上, indexList: [2, ..., 5]}
  兼下: {source: 兼, indexList: [6, ..., 9]}
  录上: {source: 录, indexList: [0, 1, 2]}
  聿上: {source: 聿, indexList: [0, 1, 2]}
  经角: {source: 经右, indexList: [0, 1]}
  马上: {source: 马, indexList: [0, 1]}
  黑五: {source: 黑上, indexList: [0, 1, 2, 3, 4]}
  止变: {source: 足旁, indexList: [3, 4, 5, 6]}
  衤二: {source: 衤, indexList: [3, 4]}
  见二: {source: 见, indexList: [0, 1]}
  土变: {source: 黑上, indexList: [5, 6, 7]}
  人改: {source: 内, indexList: [2, 3]}
  前上离: {source: 丧, indexList: [2, 3, 4]}
  卜离: {source: 不, indexList: [2, 3]}
  今上: {source: 今, indexList: [0, 1]}
  七变: {source: 长, indexList: [1, 2]}
  化右变: {source: 龙, indexList: [2, 3]}
